# Attention Circuits Control Laboratory - I/O Synchbox
# Hardware component Makefile.
# Written by Christopher Thomas.
# Copyright (c) 2021 by Vanderbilt University. This work is released under
# the Creative Commons Attribution-ShareAlike 4.0 International License.

default: helpscreen

helpscreen:
	@echo ""
	@echo "Targets:  clean release"
	@echo ""

clean:

#	make -C v2-shield clean
#	make -C v2-frontpanel clean
#	make -C v2-backpanel clean

release:

#	make -C v2-shield release
#	make -C v2-frontpanel release
#	make -C v2-backpanel release

#
# This is the end of the file.
