# Attention Circuits Control Laboratory - I/O Synchbox
# Hardware component Makefile.
# Written by Christopher Thomas.
# Copyright (c) 2021 by Vanderbilt University. This work is released under
# the Creative Commons Attribution-ShareAlike 4.0 International License.

default: helpscreen

helpscreen:
	@echo ""
	@echo "Targets:  release"
	@echo ""


SRCBASE=joystick
DSTBASE=joystick-2016

UPATH=../../../../utils/

clean:
	rm -f packages/*

# FIXME - Not much to do. This is a skeleton project.
release: clean
	cp schematics/$(SRCBASE)-schem.png packages/$(DSTBASE)-schem.png

#
# This is the end of the file.
