# NOTE - The rebuild script already pre-cleans, so no "clean" call needed.

default: helpscreen

helpscreen:
	@echo ""
	@echo "Targets:  clean  rebuild"
	@echo ""

clean:
	rm -f *.jpg

rebuild:
	./rebuild-images.sh

# This is the end of the file.
